language: php
php:
- 7.1
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_b7d425d3bc0a_key -iv $encrypted_b7d425d3bc0a_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host 101.132.169.136\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
script:
- echo "hello world"
after_success:
- ssh -p $DEPLOY_PORT $DEPLOY_USER@$DEPLOY_HOST 'cd /var/www/admin && git pull'
- ssh -p $DEPLOY_PORT $DEPLOY_USER@$DEPLOY_HOST 'cd /var/www/admin && composer install'
- ssh -p $DEPLOY_PORT $DEPLOY_USER@$DEPLOY_HOST 'cd /var/www/admin && npm run publish'
env:
  global:
  - secure: acZa1tNHLHAMNo44qp4kfvSWu7yKy0neJZexkv2W3Bx2914G8ZU9GY6V4Isf+u60XufbDQDSFyPTeFAH4mpa2aJRKsjz1qPYg6wl2AkVbrki/L4vbMZFhW3162+v6ylsGnuytEbOLg3XRvXsq8ElfBjD/cdpGhBV6x1ntcl9r1EkSkwQlc/ZwkRcAjV4g8n1rsE9XJfa5FgOowXS9NI/I2jS7WWixkcATh+l/m9c4soAmPliBSc841wVr04Bf1Tf6ApeaPY4YFSbDnc/XsagRfEghL4B5oGY9a8q9BR//clb6HkopQ4waVy/pcCk+xiyDn1K6XsEfKdntRu51H+2mDSEK9iGG+bxV/8EJBVjUPFskikOw2xpv/PcRgjQqIrvuER8xgVbHNH2vaZMU2pySiCCo3vIKRBeX9ngsEpk+TRFYQQXrlHcx4WybPk/PImaJncFnyRld3oAp+cElY7hjtdU3ltLuJDHzQCdTd+8zouTX/FxwW3GW2APKRMa0OzS0qlKCDuz49dzs5Wlpc38P5hhPE52FW46tQ2Iiy/4yO5zHYN+JkYdO1gJzP1jfQEjvPOGRfFSdetG/ALg5L3pVcjbjcO9dcXgR2/z1MxKI8i3e+tNub6DGbLZ+vE7Q1hhb7CplZknsARto+vtkBKEVVazNXqoMrutmSoOTT07Fqg=
  - secure: m53C5JrSO2fPkkcwcNRjedWFTpMKhh69zk+GZTLoKCiXmEyD+6ucJtPdT25s2cdN0wMabtxxiJKbYipkSZ097/ZEoV/XTj9vkYNBKupQYnKoM2bLT26XL76tIl8dRJT2qGmrPUQid+iGTgQDVquqNpPjv+LjIZ3I8MaPqjnSGDhPg9CwVGsUwyKNvUz2u0Bg4hVXKykzjm+CL0L9jB3VgojJzgkXQUV0i40BbFmWqkseGDlcr4m1M8Mx7LW0D4Xyyt9t0H/2z9GZD8avt9iCkXS0qsjjZK1gvEivAzjzep2PUJbknFMUBBCfXAdH/XOc2JZhAYjJWN4GXA6truNXOMcU4iBs7fYUCbxdPWOCRzSvxDjhlaaW3kYre+1WxEklUjxgc4KcUTi4Z3IqKLs+upuV6oPf4PMe0dzsJa9zLt2t2kE9624K2AL6SehZEYFmaYZ9MWN3r8tU8nKEuWRpwTYaMTc0pg8jELrhWIrBpx2I8IYF6PNGSYKMe3MCQFuTzGPjEUSVpk9ehd2nTn5YAURJvMRizAQAkiIb7J9Ifhy/6rz1QSuKSWOrtVUWSESbWrAA6ClrQNlqsTGxnhwjDPnSw3gxeqHqcvta3m+nkLqIXugZIi7I7+FJkj9TfivnxnjoMFfUvAwr/fmEYUKLThCnYDXer0C/FffsF+b/Hlc=
  - secure: mP1QHMEybY6ITUHPvbAJzQeKbRiN4o8vogn1OiK7VTXr6xvmf0u/3F1zEVaMgsnAA+1TltI/NjfSNpgA0DeHdYFOJ8tQ0HGAg3Tayo9LF5sKNJXgNQyVlouD5eGCArjoe8Ef7Ez0mI/3GAToCDGHLCEJsU1yN+mvfYmfNbxWiPAu+/+m9ZZQFAeaN5Fd9+/jxryvasf/sF3J9irJnqHxlXrc8iSiylS2ow+pMxho4EQkDZK0HuJPUYto3bQPBo8YJQRdqNVWt54C0LQhiKZUI2NbJHGOxIki18YEMbbI7uxL8DzJiHT9EylTNQBkZZi8BnCqS0KcBsMqsRRoeJry0ZcssJd7dlrMy8yZ3JWfu0sstIFWbQokAehGlrMDZrXqSbbpO8Y1Atpvf30+fiesF8oyxKsTOVswunWq47mt6N2n8wWAgccaF07ryIbn9Nz2j69bn7WlYapcxGf22WOLP5PP581Kg1qIpgOWqkbPGrWc+72e/ekAcPTuF3M31H7FPLxE00dPlCF2GNNP9Z8m6JxarfxAvXfGmNVoFnL8KbSqfuH6zpmjIoH/gcB05MTprsqcClIHDGp1ScU0CQtU5Oj/OFJYL6ufk/P1MQ1Ag1hSvAl6C90tXW94izmUESIDX0kPXV1cx3r5qGfPcwWU5oNBKEXGk9W+E5dZH7hQuME=
