language: php

php:
  - 7.1

before_install:
  - openssl aes-256-cbc -K $encrypted_b7d425d3bc0a_key -iv $encrypted_b7d425d3bc0a_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - echo -e "Host $STAGING_SERVER\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - echo -e "Host $PRODUCTION_SERVER\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

script:
- echo "hello world"

deploy:
  - provider: script
    skip_cleanup: true
    script:
      ssh -p $PORT $USER@$STAGING_SERVER 'cd /var/www/admin && git pull' &&
      ssh -p $PORT $USER@$STAGING_SERVER 'cd /var/www/admin && composer install' &&
      ssh -p $PORT $USER@$STAGING_SERVER 'cd /var/www/admin && yarn' &&
      ssh -p $PORT $USER@$STAGING_SERVER 'cd /var/www/admin && npm run build' &&
      ssh -p $PORT $USER@$STAGING_SERVER 'cd /var/www/admin && npm run publish'
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script:
      ssh -p $PORT $USER@$PRODUCTION_SERVER 'cd /var/www/admin && git pull' &&
      ssh -p $PORT $USER@$PRODUCTION_SERVER 'cd /var/www/admin && composer install' &&
      ssh -p $PORT $USER@$PRODUCTION_SERVER 'cd /var/www/admin && yarn' &&
      ssh -p $PORT $USER@$PRODUCTION_SERVER 'cd /var/www/admin && npm run build' &&
      ssh -p $PORT $USER@$PRODUCTION_SERVER 'cd /var/www/admin && npm run publish'
    on:
      branch: deploy

